const checkinConstants = {
    CHECKIN_INDIAN: 'GUEST_CHECKIN_INDIAN',
    CHECKIN_FOREIGNER: 'GUEST_CHECKIN_FOREIGNER',
    
    CHECKIN_SUCCESS: 'GUEST_CHECKIN_SUCCESS',
    CHECKIN_FAILURE: 'GUEST_CHECKIN_FAILURE',
};

export default checkinConstants;